title: "HOANG Minh-Ha"
description: "Data Engineer | Data Analyst"
markdown: GFM
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: pages
    values:
      author_profile: true

sidebar:
  - title: "√Ä propos"
    text: "Bienvenue sur mon site !"
  - title: "Contact"
    text: "üì© hello@exemple.com"

# theme: jekyll-theme-leap-day  # title/description (OK), ressemble √† la doc python, sections cliquables sur volet gauche (mais trop de sections)
# theme: jekyll-theme-hacker # title/description (OK), lien url (OK), niveau des sections (KO), ic√¥ne section d√©pli√©e (OK), black theme (OK)
# theme: jekyll-theme-modernist # title/description (OK), lien url (OK), niveau des sections (KO), ic√¥ne section d√©pli√©e (OK)
# theme: jekyll-theme-slate # title/description (OK), lien url (OK), niveau des sections (KO), ic√¥ne section d√©pli√©e (OK)
# theme: jekyll-theme-architect # title/description (OK), lien url (OK), niveau des sections (OK), ic√¥ne section d√©pli√©e (KO)
# theme: jekyll-theme-merlot  # title/description (OK), ic√¥ne section d√©pli√©e (OK), theme qui fait un peu "diplome", commentaires en gras
# theme: jekyll-theme-midnight  # black theme (OK), ic√¥ne section d√©pli√©e (OK), niveau des sections (KO)
# theme: jekyll-theme-cayman  # title/description (OK), bani√®re verte qui prend trop de place
# theme: jekyll-theme-minimal  # prend une grosse partie √† gauche pour rien, ic√¥ne section d√©pli√©e (OK)


# https://github.com/pages-themes/leap-day